name: "🐞 Bug Report"
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill in the details below so we can help you faster.

  - type: input
    id: sdk_version
    attributes:
      label: SDK Version
      description: What version of the SDK/library are you using?
      placeholder: e.g., v1.2.3
    validations:
      required: true

  - type: input
    id: platform
    attributes:
      label: Platform & Environment
      description: OS/Platform and version (e.g., iOS 17, Android 14, Node.js 18)
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: Describe the Bug
      description: What happened? What did you expect to happen instead?
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide steps so we can reproduce the issue
      placeholder: |
        1. Initialize SDK
        2. Call `initPayment`
        3. App crashes with error XYZ
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste error logs, stack traces, or screenshots here

  - type: dropdown
    id: urgency
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
        - Critical
